import type { Config } from "tailwindcss";
import tailwindAnimate from "tailwindcss-animate";
import tailwindTypography from "@tailwindcss/typography";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        md: "2rem",
      },
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        serif: ['Lora', 'Georgia', 'serif'],
        sans: ['Lato', '-apple-system', 'sans-serif'],
      },
      colors: {
        "vibe-pink": "#f472b6",
        "vibe-sky": "#7dd3fc",
        "vibe-teal": "#2dd4bf",
        "pearl-light": "#f8f8f8",
        "surface-dim": "#dcdad5",
        "on-background": "#1c1c19",
        "inverse-on-surface": "#f3f0eb",
        "primary-fixed-dim": "#b0ceba",
        "on-surface": "#1c1c19",
        "on-secondary": "#ffffff",
        "surface-tint": "#496454",
        "error": "#ba1a1a",
        "on-primary-fixed": "#062014",
        "outline": "#727973",
        "on-surface-variant": "#424844",
        "surface-container-low": "#f6f3ee",
        "surface-container-high": "#ebe8e3",
        "error-container": "#ffdad6",
        "on-secondary-container": "#4f6a5b",
        "tertiary-container": "#222825",
        "surface-container": "#f0ede9",
        "tertiary-fixed": "#dee4de",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#cbead6",
        "on-secondary-fixed-variant": "#324c3e",
        "on-tertiary-fixed-variant": "#424844",
        "tertiary-fixed-dim": "#c2c8c2",
        "outline-variant": "#c2c8c2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b0ceba",
        "secondary-container": "#cbead6",
        "primary-container": "#122c1f",
        "on-tertiary-fixed": "#171d1a",
        "surface-container-highest": "#e5e2dd",
        "primary-fixed": "#cbead6",
        "tertiary": "#0e1410",
        "on-primary-fixed-variant": "#324c3e",
        "inverse-primary": "#b0ceba",
        "on-secondary-fixed": "#052014",
        "surface-variant": "#e5e2dd",
        "on-tertiary-container": "#898f8b",
        "surface": "#fcf9f4",
        "on-primary-container": "#789583",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f4",
        "inverse-surface": "#31302d",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        main: "hsl(var(--foreground))",
        heading: "hsl(var(--heading))",
        sage: {
          DEFAULT: "hsl(var(--sage))",
          light: "hsl(var(--sage-light))",
        },
        gold: {
          DEFAULT: "hsl(var(--gold))",
          light: "hsl(var(--gold-light))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.8s ease-out forwards",
      },
    },
  },
  plugins: [tailwindAnimate, tailwindTypography],
} satisfies Config;
