-- Seed contact_sections table with default data
INSERT INTO contact_sections (
  id,
  eyebrow_en,
  eyebrow_ja,
  title_line_1_en,
  title_line_1_ja,
  title_line_2_en,
  title_line_2_ja,
  title_line_2_html,
  description_en,
  description_ja,
  primary_button_label_en,
  primary_button_label_ja,
  primary_button_url,
  background_image_url,
  overlay_opacity,
  is_published,
  created_at,
  updated_at
) VALUES (
  1,
  'Get In Touch',
  'お問い合わせ',
  'Let''s build something',
  '共に創りましょう',
  'remarkable together.',
  '素晴らしいものを。',
  '<span class="italic">remarkable together.</span>',
  'Whether you''re looking to reimagine your brand strategy, scale your digital presence, or drive measurable growth — I''d love to hear from you.',
  'ブランド戦略の再構築、デジタルプレゼンスの拡大、または測定可能な成長の推進をお考えでしたら、ぜひお気軽にご連絡ください。',
  'Start a Conversation',
  '会話を始める',
  '',
  '',
  0.5,
  true,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  eyebrow_en = EXCLUDED.eyebrow_en,
  eyebrow_ja = EXCLUDED.eyebrow_ja,
  title_line_1_en = EXCLUDED.title_line_1_en,
  title_line_1_ja = EXCLUDED.title_line_1_ja,
  title_line_2_en = EXCLUDED.title_line_2_en,
  title_line_2_ja = EXCLUDED.title_line_2_ja,
  title_line_2_html = EXCLUDED.title_line_2_html,
  description_en = EXCLUDED.description_en,
  description_ja = EXCLUDED.description_ja,
  primary_button_label_en = EXCLUDED.primary_button_label_en,
  primary_button_label_ja = EXCLUDED.primary_button_label_ja,
  primary_button_url = EXCLUDED.primary_button_url,
  background_image_url = EXCLUDED.background_image_url,
  overlay_opacity = EXCLUDED.overlay_opacity,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();
